apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmezd7356-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmezd7356-tenant-component
    app.kubernetes.io/part-of: loadmezd7356-tenant-app
  name: loadmezd7356-tenant-component
  namespace: loadmezd7356-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmezd7356-tenant-component
    weight: null
status: {}
